# makefile for xmhf-startup component
# author: amit vasudevan (amitvasudevan@acm.org)

# source files
AS_SOURCES =

C_SOURCES =  runtime.c
C_SOURCES += rntm-data.c
C_SOURCES += lhv.c
C_SOURCES += lhv-console.c
C_SOURCES += lhv-timer.c
C_SOURCES += lhv-pic.c

C_SOURCES += ./arch/x86/rntm-x86-data.c

# targets
include ../runtime.mk

