name: Build XMHF with TrustVisor

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'i386'
          - 'amd64'
        compile_mode:
          - 'debug'
          - 'release'
        optimize_mode:
          - 'O0'
          - 'O3'

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        cpuid

