name: Build XMHF with TrustVisor

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'x86'
          - 'x86_64'
        compile_mode:
          - 'debug'
          - 'release'

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install \
                      openssh-server tmux vim git aptitude \
                      pbuilder texinfo ruby build-essential autoconf libtool \
                      crossbuild-essential-i386 gcc-mingw-w64 \
                      -y
    - name: Build
      run: |
        ./.github/build.sh \
          ${{ matrix.target_arch }} \
          ${{ matrix.compile_mode }}
    - name: Release
      uses: actions/upload-artifact@v2
      with:
        name: boot-${{ matrix.target_arch }}-${{ matrix.compile_mode }}
        path: |
          xmhf/src/xmhf-core/xmhf-secureloader/sl_syms.exe
          xmhf/src/xmhf-core/xmhf-bootloader/init_syms.exe
          xmhf/src/xmhf-core/xmhf-runtime/runtime.exe
          hypervisor-${{ matrix.target_arch }}.bin.gz
          init-${{ matrix.target_arch }}.bin
    - name: Build pal_demo Linux
      if: ${{ matrix.compile_mode == 'debug' }}
      run: |
        ./.github/build_pal_demo.sh linux ${{ matrix.target_arch }}
    - name: Release pal_demo Linux
      if: ${{ matrix.compile_mode == 'debug' }}
      uses: actions/upload-artifact@v2
      with:
        name: pal_demo-linux-${{ matrix.target_arch }}
        path: |
          hypapps/trustvisor/pal_demo/main
          hypapps/trustvisor/pal_demo/test
          hypapps/trustvisor/pal_demo/test_args
    - name: Build pal_demo Windows
      if: ${{ matrix.compile_mode == 'debug' }}
      run: |
        ./.github/build_pal_demo.sh windows ${{ matrix.target_arch }}
    - name: Release pal_demo Windows
      if: ${{ matrix.compile_mode == 'debug' }}
      uses: actions/upload-artifact@v2
      with:
        name: pal_demo-windows-${{ matrix.target_arch }}
        path: |
          hypapps/trustvisor/pal_demo/main.exe
          hypapps/trustvisor/pal_demo/test.exe
          hypapps/trustvisor/pal_demo/test_args.exe

