name: Check VMCS macros

on: ["push", "pull_request"]

jobs:
  vmcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check VMCS macros
      run: |
        python3 tools/vmcs/read_macro.py
        python3 tools/vmcs/read_macro.py > vmcs.csv
    - name: Release vmcs.csv
      uses: actions/upload-artifact@v3
      with:
        path: vmcs.csv

